### ISSUE TITLE
Create weather.html

### ISSUE THREAD

**Issue by mariaalouisaa** [ahoat/HTTP-Project#1]
- [x] Include the header
- [x] Have button to navigate to weather
- [x] Fetch weather API
- [x] Create a search bar
- [x] Display description 
- [x] Display temperate
- [x] Display city name

**Comment by mariaalouisaa** [comment]
Something I didn't mention yesterday, is the weather api's default response gives the temperature in Kelvin so we need to add a bit to the fetch URL so that it returns data in Celcius. 

api.openweathermap.org/data/2.5/weather?q=${city name}&units=metric&appid=${API key}

 https://openweathermap.org/current

**Comment by ahoat** [comment]
I think I have covered everything in this issue with my latest PR.
I did a manual calculation to change from Kelvin to Celcius.
Stretch goal for this is to try and add the icons to the weather but not 100% sure they are available on my freemium account.
