### ISSUE TITLE
As a confused user, I want to be told when something goes wrong

### ISSUE THREAD

**Issue by mariaalouisaa** [ahoat/HTTP-Project#5]
Add alert to user in the catch

**Comment by ahoat** [comment]
- [x] create visual feedback on weather page if search item not found
- [ ] create visual feedback on news page if search item not found

**Comment by mariaalouisaa** [comment]
1. Shall we do this simply with an `alert()`?
2. Or we can make a pop-up message in HTML with our own CSS? We can give it `visibility: hidden` by default and then remove it in the `catch`. 
The second option looks nicer BUT it doesn't do well in terms of accessibility. What do you think?

**Comment by ahoat** [comment]
I've added some JS to the weather .catch which I think helps us overcome the accessibility problem.

**Comment by mariaalouisaa** [comment]
Yup, after the next pull I think this issue can be closed
