### ISSUE TITLE
Add a README

### ISSUE THREAD

**Issue by mariaalouisaa** [ahoat/HTTP-Project#6]
A clearly defined user journey, documented in your readme

**Comment by mariaalouisaa** [comment]
I made a start on the read me (mostly coping what we wrote on monday in those slides).

Still a few bits to add... Also feel free to edit whatever in it!

**Comment by mariaalouisaa** [comment]
Love the changes you made to the readme! 👍

**Comment by ahoat** [comment]
I've added some screenshots but not sure how to resize them with markdown.
However, we think we can close this issue now
